<template>
  <AuthenticatedLayout>
    <Head title="Automatic Alerts" />

    <div class="py-12">
      <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
        <!-- Header -->
        <div class="mb-8">
          <div class="flex items-center justify-between">
            <div>
              <h2 class="text-3xl font-bold leading-tight text-gray-900">
                Automatic Alert System
              </h2>
              <p class="mt-2 text-sm text-gray-600">
                Threshold-based alerts automatically generated by the surveillance system
              </p>
            </div>
            <div class="flex space-x-4">
              <button
                @click="triggerCheck"
                :disabled="isChecking"
                class="inline-flex items-center px-4 py-2 bg-blue-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-blue-700 focus:bg-blue-700 active:bg-blue-900 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition ease-in-out duration-150 disabled:opacity-50"
              >
                <svg v-if="isChecking" class="animate-spin -ml-1 mr-3 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                {{ isChecking ? 'Checking...' : 'Check Now' }}
              </button>
            </div>
          </div>
        </div>

        <!-- Statistics Cards -->
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-8">
          <div class="bg-white overflow-hidden shadow rounded-lg">
            <div class="p-5">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <div class="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center">
                    <svg class="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
                    </svg>
                  </div>
                </div>
                <div class="ml-5 w-0 flex-1">
                  <dl>
                    <dt class="text-sm font-medium text-gray-500 truncate">Total Automatic Alerts</dt>
                    <dd class="text-lg font-medium text-gray-900">{{ stats.total_automatic_alerts }}</dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>

          <div class="bg-white overflow-hidden shadow rounded-lg">
            <div class="p-5">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <div class="w-8 h-8 bg-yellow-500 rounded-full flex items-center justify-center">
                    <svg class="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                    </svg>
                  </div>
                </div>
                <div class="ml-5 w-0 flex-1">
                  <dl>
                    <dt class="text-sm font-medium text-gray-500 truncate">Draft Alerts</dt>
                    <dd class="text-lg font-medium text-gray-900">{{ stats.draft_alerts }}</dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>

          <div class="bg-white overflow-hidden shadow rounded-lg">
            <div class="p-5">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <div class="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center">
                    <svg class="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
                    </svg>
                  </div>
                </div>
                <div class="ml-5 w-0 flex-1">
                  <dl>
                    <dt class="text-sm font-medium text-gray-500 truncate">Published Alerts</dt>
                    <dd class="text-lg font-medium text-gray-900">{{ stats.published_alerts }}</dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>

          <div class="bg-white overflow-hidden shadow rounded-lg">
            <div class="p-5">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <div class="w-8 h-8 bg-red-500 rounded-full flex items-center justify-center">
                    <svg class="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                    </svg>
                  </div>
                </div>
                <div class="ml-5 w-0 flex-1">
                  <dl>
                    <dt class="text-sm font-medium text-gray-500 truncate">Severe Alerts</dt>
                    <dd class="text-lg font-medium text-gray-900">{{ stats.severe_alerts }}</dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Filters -->
        <div class="mb-6 bg-white p-4 rounded-lg shadow">
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Status</label>
              <select
                v-model="filters.status"
                @change="updateFilters"
                class="block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="all">All Statuses</option>
                <option value="draft">Draft</option>
                <option value="published">Published</option>
                <option value="archived">Archived</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Alert Level</label>
              <select
                v-model="filters.alert_level"
                @change="updateFilters"
                class="block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="all">All Levels</option>
                <option value="moderate">Moderate</option>
                <option value="high">High</option>
                <option value="severe">Severe</option>
              </select>
            </div>
          </div>
        </div>

        <!-- Alerts List -->
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <ul class="divide-y divide-gray-200">
            <li v-for="alert in alerts.data" :key="alert.id" class="px-6 py-4">
              <div class="flex items-center justify-between">
                <div class="flex items-center space-x-4">
                  <!-- Alert Level Badge -->
                  <div
                    :class="[
                      'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
                      getAlertLevelClass(alert.alert_level)
                    ]"
                  >
                    {{ alert.alert_level.toUpperCase() }}
                  </div>

                  <!-- Alert Details -->
                  <div>
                    <h3 class="text-lg font-semibold text-gray-900">
                      {{ alert.alert_title }}
                    </h3>
                    <div class="mt-1 flex items-center space-x-4 text-sm text-gray-600">
                      <span>{{ alert.disease?.name }}</span>
                      <span>•</span>
                      <span>{{ alert.municipality?.name }}</span>
                      <span>•</span>
                      <span>{{ alert.number_of_cases }} cases</span>
                      <span>•</span>
                      <span>{{ formatDate(alert.created_at) }}</span>
                    </div>
                  </div>
                </div>

                <!-- Actions -->
                <div class="flex items-center space-x-3">
                  <!-- Status Badge -->
                  <span
                    :class="[
                      'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
                      getStatusClass(alert.status)
                    ]"
                  >
                    {{ alert.status.toUpperCase() }}
                  </span>

                  <!-- Action Buttons -->
                  <div class="flex space-x-2">
                    <Link
                      :href="route('automatic-alerts.show', alert.id)"
                      class="text-blue-600 hover:text-blue-900"
                    >
                      View
                    </Link>

                    <button
                      v-if="alert.status === 'draft'"
                      @click="publishAlert(alert.id)"
                      class="text-green-600 hover:text-green-900"
                    >
                      Publish
                    </button>

                    <button
                      v-if="alert.status === 'published'"
                      @click="archiveAlert(alert.id)"
                      class="text-gray-600 hover:text-gray-900"
                    >
                      Archive
                    </button>
                  </div>
                </div>
              </div>
            </li>
          </ul>

          <!-- Pagination -->
          <div v-if="alerts.last_page > 1" class="px-6 py-3 border-t border-gray-200">
            <nav class="flex items-center justify-between">
              <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
                <div>
                  <p class="text-sm text-gray-700">
                    Showing
                    <span class="font-medium">{{ alerts.from }}</span>
                    to
                    <span class="font-medium">{{ alerts.to }}</span>
                    of
                    <span class="font-medium">{{ alerts.total }}</span>
                    results
                  </p>
                </div>
                <div>
                  <nav class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px">
                    <Link
                      v-for="link in alerts.links"
                      :key="link.url || link.label"
                      :href="link.url || '#'"
                      :class="[
                        'relative inline-flex items-center px-4 py-2 border text-sm font-medium',
                        link.active
                          ? 'z-10 bg-blue-50 border-blue-500 text-blue-600'
                          : 'bg-white border-gray-300 text-gray-500 hover:bg-gray-50',
                        !link.url && 'cursor-not-allowed opacity-50'
                      ]"
                      v-html="link.label"
                    />
                  </nav>
                </div>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </AuthenticatedLayout>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'

interface Alert {
  id: number
  alert_title: string
  alert_level: string
  status: string
  number_of_cases: number
  created_at: string
  disease?: {
    id: number
    name: string
  }
  municipality?: {
    id: number
    name: string
  }
}

interface Props {
  alerts: {
    data: Alert[]
    from: number
    to: number
    total: number
    last_page: number
    links: Array<{
      url: string | null
      label: string
      active: boolean
    }>
  }
  stats: {
    total_automatic_alerts: number
    draft_alerts: number
    published_alerts: number
    severe_alerts: number
  }
  filters: {
    status?: string
    alert_level?: string
  }
}

const props = defineProps<Props>()

const isChecking = ref(false)
const filters = reactive({
  status: props.filters.status || 'all',
  alert_level: props.filters.alert_level || 'all'
})

const getAlertLevelClass = (level: string) => {
  switch (level) {
    case 'moderate':
      return 'bg-yellow-100 text-yellow-800'
    case 'high':
      return 'bg-orange-100 text-orange-800'
    case 'severe':
      return 'bg-red-100 text-red-800'
    default:
      return 'bg-gray-100 text-gray-800'
  }
}

const getStatusClass = (status: string) => {
  switch (status) {
    case 'draft':
      return 'bg-gray-100 text-gray-800'
    case 'published':
      return 'bg-green-100 text-green-800'
    case 'archived':
      return 'bg-blue-100 text-blue-800'
    default:
      return 'bg-gray-100 text-gray-800'
  }
}

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const updateFilters = () => {
  router.get(route('automatic-alerts.index'), filters, {
    preserveState: true,
    replace: true
  })
}

const triggerCheck = async () => {
  isChecking.value = true
  try {
    router.post(route('automatic-alerts.trigger-check'), {}, {
      onFinish: () => {
        isChecking.value = false
      }
    })
  } catch (error) {
    isChecking.value = false
  }
}

const publishAlert = (alertId: number) => {
  if (confirm('Are you sure you want to publish this alert?')) {
    router.post(route('automatic-alerts.publish', alertId))
  }
}

const archiveAlert = (alertId: number) => {
  if (confirm('Are you sure you want to archive this alert?')) {
    router.post(route('automatic-alerts.archive', alertId))
  }
}
</script>
